name: Build
on: [push, pull_request]

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ ninja-build ccache

    - name: llvm
      run: |
        cd wamr/wamr-compiler
        ./build_llvm.sh

    - name: wamrc
      run: |
        cd wamr/wamr-compiler
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wamrc-linux
        compression-level: 9
        path: |
          wamr/wamr-compiler/build/wamrc

  windows:
    name: windows
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install packages
      shell: bash
      run: |
        pip install requests

    - name: llvm
      shell: bash
      run: |
        cd wamr/wamr-compiler
        ./build_llvm.py

    - name: wamrc
      shell: bash
      run: |
        cd wamr/wamr-compiler
        mkdir build
        cd build
        cmake ..
        cmake --build . --config release

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wamrc-windows
        compression-level: 9
        path: |
          wamr/wamr-compiler/build/Release/wamrc.exe
